name: Fly Deploy
on: [push]
# on:
#   push:
#     branches:    
#       - 'main'
#   workflow_dispatch:
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - uses: actions/setup-node@v3
        with:
          node-version: 18.4.0
          cache: 'yarn'
      - run: ./bin/bt build --environment=production
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
      # - uses: superfly/flyctl-actions/setup-flyctl@master
      # - run: flyctl deploy --remote-only