on: [ push, workflow_dispatch ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version-file: ".bun-version"
    - run: bun install
    - run: bun run eleventy
    # - name: Publish to Cloudflare Pages
    #   uses: cloudflare/pages-action@v1
    #   with:
    #     apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    #     accountId: eae30e90d3179c4c3ba81a6b7d1151b0
    #     projectName: vincecima-com
    #     directory: _site
